### ISSUE TITLE
cannot declare and use a class or define

### ISSUE THREAD

**Issue by logicminds** [nwops/puppet-repl#11]
```
>> define foo($attr1 = 'one'){}
 =>
>> foo{'hello': attr1 => 'test'}
 => Evaluation Error: Error while evaluating a Resource Statement, Invalid resource type foo at line 1:1
>>

```

Another example

```
>> class foo($var1 ='value1'){ file{'/tmp/test':}}
 =>
>> krt
{
 :definitions => [],
 :hostclasses => [
  [0] "",
  [1] "settings"
 ],
 :nodes       => []
}
>> include foo
 => Evaluation Error: Error while evaluating a Function Call, Could not find class ::foo for foo.example.com at line 1:1

```

**Comment by logicminds** [comment]
However, if the class is in my module path, I can include the class and `krt` which show the classes.

```
>> include apache
 =>
>> krt
{
 :definitions => [
  [0] "concat",
  [1] "concat::fragment",
  [2] "apache::mod",
  [3] "apache::mpm",
  [4] "apache::vhost"
 ],
 :hostclasses => [
  [ 0] "",
  [ 1] "settings",
  [ 2] "apache",
  [ 3] "apache::params",
  [ 4] "apache::version",
  [ 5] "apache::service",
  [ 6] "apache::default_mods",
  [ 7] "apache::mod::actions",
  [ 8] "apache::mod::authn_core",
  [ 9] "apache::mod::cache",
  [10] "apache::mod::ext_filter",
  [11] "apache::mod::mime",
  [12] "apache::mod::mime_magic",
  [13] "apache::mod::rewrite",
  [14] "apache::mod::speling",
  [15] "apache::mod::suexec",
  [16] "apache::mod::version",
  [17] "apache::mod::vhost_alias",
  [18] "apache::mod::cgi",
  [19] "apache::mod::alias",
  [20] "apache::mod::authn_file",
  [21] "apache::mod::autoindex",
  [22] "apache::mod::dav",
  [23] "apache::mod::dav_fs",
  [24] "apache::mod::deflate",
  [25] "apache::mod::dir",
  [26] "apache::mod::negotiation",
  [27] "apache::mod::setenvif",
  [28] "apache::mod::filter",
  [29] "apache::mod::authz_user",
  [30] "apache::default_confd_files",
  [31] "apache::mod::prefork"
 ],
 :nodes       => []
}

```

**Comment by hlindberg** [comment]
That problem is probably from the fact that evaluation of is a no-op for all definition. What is needed is to process all the definitions (i.e. define, class, function, etc).
The Compiler is using the E4ParserAdapter to parse. You can see that it uses Puppet::Parser::AST::PopsBridge to adapt to the 3.x Compiler. An instance of a PopsBridge::Program is created, and the compiler will call its `instantiate` method. That will process all definitions. 

You should be able to do the same as E4ParserAdapter.

**Comment by logicminds** [comment]
@hlindberg 

So basically I would have to detect when its a "definition" and then execute the following:

`AST::Hostclass.new('', :code => ast_code)`.  

Do I need to add it to the scope or something in order for the next eval to run with the new definations?

Below is the code from Puppet::E4ParserAdapter#parse function  
```
def parse(string = nil)
    self.string= string if string
    parser = Pops::Parser::EvaluatingParser.singleton
    parse_result =
    if @use == :string
      # Parse with a source_file to set in created AST objects (it was either given, or it may be unknown
      # if caller did not set a file and the present a string.
      #
      parser.parse_string(@string, @file || "unknown-source-location")
    else
      parser.parse_file(@file)
    end

    # the parse_result may be
    # * empty / nil (no input)
    # * a Model::Program
    # * a Model::Expression
    #
    model = parse_result.nil? ? nil : parse_result.current
    args = {}
    Pops::Model::AstTransformer.new(@file).merge_location(args, model)

    ast_code =
    if model.is_a? Pops::Model::Program
      AST::PopsBridge::Program.new(model, args)
    else
      args[:value] = model
      AST::PopsBridge::Expression.new(args)
    end

    # Create the "main" class for the content - this content will get merged with all other "main" content
    AST::Hostclass.new('', :code => ast_code)
  end
```

**Comment by hlindberg** [comment]
The key is `AST::PopsBridge::Program.new(model, args)` - that is what the compiler wraps in a hostclass called '' (empty string - aka "main"). If you just want to trigger what the compiler will trigger, you can call `ast_code.instantiate("modulename")`. See the AST::PopsBridge for what it does when "instantiate" is called (it processes all the definitions in the program).

Does that help?

**Comment by logicminds** [comment]
I did manage to get this working for classes and definitions using known_resource_types.import_ast.

However it fails on functions because loaders.find_loader fails to find a loader and raises an error.  Any idea why puppet can't find the loader?

**Comment by logicminds** [comment]
Furthermore even firing up a new irb session and running Puppet.lookup(:loaders) causes the same error.

**Comment by hlindberg** [comment]
I messaged you on slack
