### ISSUE TITLE
emacs integration

### ISSUE THREAD

**Issue by igalic** [nwops/puppet-repl#22]
emacs has excelent integration for all kinds of repls:

* [CIDER](https://cider.readthedocs.io/en/latest/) (for clojure)
* [SLIME](https://common-lisp.net/project/slime/) or [SLY](https://github.com/joaotavora/sly) (for Common Lisp)
* [Geiser](http://www.nongnu.org/geiser/) (for Scheme)

Of course, there are also non-lisps!

* [coffee-mode](https://github.com/defunkt/coffee-mode)
* [IPython](https://tkf.github.io/emacs-ipython-notebook/) (probably also available for mere-mortal python ;)

On the ruby side of things, there's [inf-ruby](https://github.com/nonsequitur/inf-ruby) which integrates with irb and pry!

It would be great if this project could advance the [puppet-mode](https://github.com/lunaryorn/puppet-mode) with repl support! (maybe that could blow some life into puppet-mode and speed up puppet 4 support! :)

**Comment by igalic** [comment]
n.b.: @neovim has support for [term://](https://neovim.io/doc/user/term.html) which could be used to achieve the similar things — but no has started doing that so far…

**Comment by logicminds** [comment]
I think there could be a lot of cool integrations like this that could go above and beyond normal linting/testing and provide a true interactive development environment.  At this time I am swamped as it is.  I still need to add some core features to the REPL.  

While this is currently undocumented, the REPL does support STDIN.  So you could do something like:

```
echo "notify{'hello':}" | prepl -r
Ruby Version: 2.2.3
Puppet Version: 4.5.2
Puppet Repl Version: 0.2.2
Created by: NWOps <corey@nwops.io>
Type "exit", "functions", "vars", "krt", "facts", "resources", "classes",
     "play", "classification", "reset", or "help" for more information.

 => Puppet::Type::Notify {
  loglevel => notice,
   message => "hello",
      name => "hello",
     title => "hello",
  withpath => false
}

```

Although I would probably have to implement a `quiet` flag to suppress the banner from the output.

**Comment by igalic** [comment]
we fixed this upstream :D
(it's not released yet on elpa, or documented, or integrated in spacemacs, but it's merged ;)
