### ISSUE TITLE
consider including a puppet function to start the repl and wait on its exit

### ISSUE THREAD

**Issue by hlindberg** [nwops/puppet-repl#8]
When you are debugging puppet code it is difficult to figure out the state at a certain point in the logic. What you need to do then is to add calls to either notice or to include notify resources that tells you the value of some variables. What you really want to do is to have a real debugger, but being able to start the repl instead is a half decent solution.

You can add a function that when called starts the repl. User can then look at things in scope, inspect variables, conduct experiments etc. When they exit from the repl the execution continues.

The result is a poor-man's debugger, but it is better than no debugger :-)

**Comment by logicminds** [comment]
yea, I thought of that.  Almost like a binding.pry.  That would be pretty killer.

**Comment by logicminds** [comment]
I created this function here: https://gist.github.com/logicminds/3ab56cfa4611f5f23483e82a1f10c90a

However, I need to set the loaders now in order to load a real context

**Comment by hlindberg** [comment]
I took a quick look. Not sure I understand your question about “setting loaders” in order to load a real context.
- henrik

**Comment by logicminds** [comment]
This function has been released https://forge.puppet.com/nwops/repl which only works with puppet-repl 0.1.0.
