### ISSUE TITLE
consider running the full compilation

### ISSUE THREAD

**Issue by hlindberg** [nwops/puppet-repl#9]
It would be neat to run the full compilation from within the repl. i.e. for a node with cached or given facts (i.e. what master compile does). Now instead of just dumping out the catalog, you can query it while still being in the repl.

If you combine the "query the catalog" with my other proposal (a function that drops into the repl), you can also inspect what is in the catalog being built at any given point in time throughout the execution.

**Comment by logicminds** [comment]
I have added a few new features called classes and resources that allows you to list the current classes and resources in the catalog.

Also if you type `Type['title']`  ie. `File['/tmp/test']` the repl will spit out the ral version of the resource.

Is there what you were envisioning?

**Comment by hlindberg** [comment]
Looks great.

**Comment by logicminds** [comment]
It would be cool to show the resource graph or some sort of ordering.

**Comment by logicminds** [comment]
oh and I forgot you can also do this

```
>> resources 0
"Stage[main]"
>>

```

Where 0 is the array index number.

**Comment by logicminds** [comment]
released in v0.1.0
